import type { Metadata } from 'next';
import { Lexend_Deca } from 'next/font/google';
import MainLayout from '@/components/layout/Layout';

import './globals.css';
import Head from 'next/head';

const font = Lexend_Deca({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Malik Zulqurnain',
  description: 'Generated by Malik Zulqurnain',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        style={{ background: 'white' }}
        className={'relative overflow-x-hidden ' + font.className}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
